{% set name = "jellyfish" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f664520189e3ae16e0b5fee21f19d15c8926e2320fd195ccc65d96390d9e9689

build:
  number: 2
  # maturin isn't available on s390x
  skip: true  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - maturin
  run:
    - python

test:
  imports:
    - jellyfish
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jamesturk/jellyfish
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A library for doing approximate and phonetic matching of strings
  description: |
    jellyfish is a library for approximate & phonetic matching of strings.
  dev_url: https://github.com/jamesturk/jellyfish
  doc_url: https://github.com/jamesturk/jellyfish

extra:
  recipe-maintainers:
    - blabalme
    - anthchirp
