{% set name = "jellyfish" %}
{% set version = "0.8.8" %}
{% set bundle = "tar.gz" %}
{% set hash = "0506089cacf9b5897442134417b04b3c6610c19f280ae535eace390dc6325a5c" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - {{ compiler('c') }}
    - pip
    - python
  run:
    - python

test:
  imports:
    - jellyfish

about:
  home: https://github.com/jamesturk/jellyfish
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: a library for doing approximate and phonetic matching of strings.
  dev_url: https://github.com/jamesturk/jellyfish
  doc_url: https://jellyfish.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - blabalme
    - anthchirp
