{% set name = "jellyfish" %}
{% set version = "0.7.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "2264020f514fc2f4f6fdd2694eea1bd316a68ef88057f120ccb4d0f4e1b47b5e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - jellyfish

about:
  home: http://github.com/jamesturk/jellyfish
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'a library for doing approximate and phonetic matching of strings.'
  dev_url: http://github.com/jamesturk/jellyfish
  doc_url: https://jellyfish.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - blabalme
