{% set name = "jellyfish" %}
{% set version = "0.8.2" %}
{% set bundle = "tar.gz" %}
{% set hash = "a499741401512d05bbd3556e448e960bc908eba3879fb73d450e8e91566a030b" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - {{ compiler('c') }}
    - pip
    - python
  run:
    - python

test:
  imports:
    - jellyfish

about:
  home: https://github.com/jamesturk/jellyfish
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'a library for doing approximate and phonetic matching of strings.'
  dev_url: https://github.com/jamesturk/jellyfish
  doc_url: https://jellyfish.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - blabalme
