{% set name = "jellyfish" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 650ba1ddabd716499f85fae0e1f3fa3e6532a69b68985d9294e86a1e04f08f9f

build:
  number: 0
  # maturin isn't available on s390x
  skip: true  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - maturin >=0.14,<2
  run:
    - python

test:
  imports:
    - jellyfish
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jamesturk/jellyfish
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A library for doing approximate and phonetic matching of strings
  description: |
    jellyfish is a library for approximate & phonetic matching of strings.
  dev_url: https://github.com/jamesturk/jellyfish
  doc_url: https://github.com/jamesturk/jellyfish

extra:
  recipe-maintainers:
    - blabalme
    - anthchirp
