{% set name = "jellyfish" %}
{% set version = "0.6.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "f5da646c4ff578ff37695915c05eaae938b1218082bfef59f8a7183477681ab0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.oef/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - toolchain

  run:
    - python

test:
  imports:
    - jellyfish

about:
  home: http://github.com/jamesturk/jellyfish
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'a library for doing approximate and phonetic matching of strings.'
  dev_url: http://github.com/jamesturk/jellyfish
  doc_url: https://jellyfish.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
