# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Bx5YqQjbN7fE3COHH7MIsgat4HD3ij9kP9DsHGVV2S2qwe5deH0kwYSzwttMvixIj/sXxQ2uB//XYCEiGQpMVaxU8o7ZyGUKnlF0pySRUv4qcdpBcEugkvzDNm9W3w+j4IXqs0T/CLdodP4FNE2mClCG/+lk522cV1vBF3ikkfMIK4rB+h/anz9VeHXjsnrhX3hEmxMwA6v7knbRvrMGQw9VqHWLjOCxRMjs6j4KgfFAdLdVqy6JNt5tO06iUWfIx/jxC/gpeOYvkWif5aTOVfBDV2U8pVvmFAlxgdZ7YfSwTRSakMPrp7NBO1NIM2o1OOrcJ2+2kSamRcak5z2zyDW8ktUlr9GuWkW+VD65Qr0XwfeP0y+gzMPk06SXJv2dSJPB2t69s4GTbTK7yOY45jHFNimN/mwrmPKYG1Lwuge5veaq+FlAxAIr/9hFW8ssxCCt7jrX3TX7dbccCiScwgDGYjVXOgOkwcSwXUQtV1Lchvp4uUIV0ObWS+xcRPGFvO0FIJ6of40OnXfnEuncubi7x6E47loRR6eV1ufrASMEc0v6CYu+iC4WIYzvO1B4UvTyqTZj5EZv52foeYYWclmBLgi2x+eOjp8jzw/UAUwpZdYPW4T/QKhRB8FJOskLuq1nDVd8hIJWChJAv6IArfottMt4Ypslz2XEsnd4W64="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
