travis:
  secure:
    BINSTAR_TOKEN: Bx5YqQjbN7fE3COHH7MIsgat4HD3ij9kP9DsHGVV2S2qwe5deH0kwYSzwttMvixIj/sXxQ2uB//XYCEiGQpMVaxU8o7ZyGUKnlF0pySRUv4qcdpBcEugkvzDNm9W3w+j4IXqs0T/CLdodP4FNE2mClCG/+lk522cV1vBF3ikkfMIK4rB+h/anz9VeHXjsnrhX3hEmxMwA6v7knbRvrMGQw9VqHWLjOCxRMjs6j4KgfFAdLdVqy6JNt5tO06iUWfIx/jxC/gpeOYvkWif5aTOVfBDV2U8pVvmFAlxgdZ7YfSwTRSakMPrp7NBO1NIM2o1OOrcJ2+2kSamRcak5z2zyDW8ktUlr9GuWkW+VD65Qr0XwfeP0y+gzMPk06SXJv2dSJPB2t69s4GTbTK7yOY45jHFNimN/mwrmPKYG1Lwuge5veaq+FlAxAIr/9hFW8ssxCCt7jrX3TX7dbccCiScwgDGYjVXOgOkwcSwXUQtV1Lchvp4uUIV0ObWS+xcRPGFvO0FIJ6of40OnXfnEuncubi7x6E47loRR6eV1ufrASMEc0v6CYu+iC4WIYzvO1B4UvTyqTZj5EZv52foeYYWclmBLgi2x+eOjp8jzw/UAUwpZdYPW4T/QKhRB8FJOskLuq1nDVd8hIJWChJAv6IArfottMt4Ypslz2XEsnd4W64=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
